version: '3.7'
services:
  flask-app:
    image: flask-app
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    enviroment:
      TRIOTASK_DB_URI: ${TRIOTASK_DB_URI}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
    - database
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  database:
    image: database
    build: ./db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    volumes:
    - type: volume
      source: mysqlvolume
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  mysqlvolume: